import type { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react'
import ReCAPTCHA from "react-google-recaptcha";
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {

  const [ name, setName ] = useState('')
  const [ email, setEmail] = useState('')
  const [ subject, setSubject ] = useState('')
  const [ message, setMessage ] = useState('')
  const [ token, setToken ] : any = useState( null )
  

  const [ errors, setErrors] = useState( null )
  const [ success, setSuccess] = useState(  null)


  const ReCAPTCHAHandler = (token : string | null ) => {
      setToken( token );
  }


  const sendEmail = ( event : any  ) => {
    event.preventDefault();
    setErrors( null );
    setSuccess( null );

    const url = '/api/send-email';
    const body = {
        "name": name,
        "email": email,
        "subject":subject, 
        "message":message, 
        "token": token, 
    };

    axios({
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      data: body,
      url,
    }).then( ( response )=> {
      
      if( response.data.success ){
        // console.log('SUCCESS')
        setSuccess(response.data.message)
      }else if( response.data.error ){
        // console.log('ERRORS 1',response.data.error)
        setErrors(response.data.error)
      }else{
        // console.log('AXIOS RESPONSE', response.data )
        setErrors(response.data.message)
      }
    })
    .catch( (error) => {
      // console.log('ERRORS 2',error.message)
      setErrors(error.message)
    });;
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>AWS SES Lambda Emailer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📨</text></svg>`}></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        📨 AWS SES Lambda Emailer
        </h1>

        <p className={styles.description}>
          This is a super simple solution for letting you send emails through your websites "contact us" section using AWS Simple Email Service (SES) 
          , Lambda and API Gateway. 
        </p>
        <p>
        This front end tool is a demonstration website built in React using NextJS. Styling has been kept purposely basic for the sake of this demo.
        </p>

        

        <form className={styles.contactForm} onSubmit={e => sendEmail(e)}>
          <div>
            <label htmlFor='name'>Your Name</label>
            <input id='name' name='name' type='text' value={name} onChange={ e => setName(e.target.value) }/>
          </div>
          <div>
            <label htmlFor='email'>Your Email</label>
            <input id='email' name='email' type='email' value={email} onChange={ e => setEmail(e.target.value) }/>
          </div>
          <div>
            <label htmlFor='subject'>Subject</label>
            <input id='subject' name='subject' type='text' value={subject} onChange={ e => setSubject(e.target.value) }/>
          </div>
          <div>
            <label htmlFor='message'>Message</label>
            <textarea id='message' name='message' value={message} rows={5} onChange={ e => setMessage(e.target.value) }></textarea>
          </div>

          <ReCAPTCHA
              sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || ''}
              onChange={ReCAPTCHAHandler}
            />

          <div>
            <label>&nbsp;</label>
            <button type="submit">Send Email</button>
          </div>

          { errors && <div className={styles.errors}>Error: {errors}</div> }
          { success && <div className={styles.success}>✅ {success}</div> }


        </form>

        
        
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/joemore"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created By Joemore
        </a>
      </footer>
    </div>
  )
}

export default Home
